### ISSUE TITLE
Stuck On NextJS

### ISSUE THREAD

**Issue by alteredorange** [Technopathic/Virgil#1]
Cool Project! Trying to play around with it, and add it to a new Nextjs project.  I'm rather new at react and Nextjs, and can't seem to get it working. Do you have an example of how this would work with Nextjs 10 and React 17? I've tried Virgil as a component, but that's not working:

    // ./components/Vrigil.js
    import React, { useState } from 'react'
    import Virgil from 'virgil-editor'
    
    const App = () => {
    const [initial] = useState({ "blocks": [], "entityMap": {} })
    const [editor, setEditor] = useState({})

    return (
        <Virgil content={initial} onRef={ref => setEditor(ref)} startFocus={true} />
    )
    }
.

     // ./pages/edit.js
     import dynamic from 'next/dynamic'
     const Virgil = dynamic(() => import('./../components/Virgil'), { ssr: false })
    
    export default function About() {
    return (
        <>
            <Virgil />
        </>
    )
    }

Any help would be greatly appreciated, thanks!

**Comment by Technopathic** [comment]
Thanks! Hello, you do not need a `./components/virgil.js` file. 

In your `./pages/edit.js`, all you need is: 

```
import React, { useState } from 'react'
import dynamic from 'next/dynamic'
const Virgil = dynamic(() => import('virgil-editor'), { ssr: false })

const Edit = () => {
  const [ initial ] = useState({"blocks":[],"entityMap":{}})
  const [ editor, setEditor ] = useState({})

  return (
    <Virgil content={initial} onRef={ref => setEditor(ref)} startFocus={true} />
  )
}

export default Edit
```

That should be all to get started.

**Comment by alteredorange** [comment]
Super, thanks!
